package miden:basic-wallet-tx-script@1.0.0;

world basic-wallet-tx-script-world {
    include miden:core-intrinsics/intrinsics@1.0.0;
    include miden:core-stdlib/stdlib@1.0.0;
    include miden:core-base/base@1.0.0;

    import miden:basic-wallet/basic-wallet@1.0.0;
    export miden:base/transaction-script@1.0.0;
}
